<a href="https://colab.research.google.com/github/sytluc0803/MSSP607/blob/main/Modules/Week_5/Week_5_Ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import userdata
import os

github_token = userdata.get('Git_Key')
owner = 'sytluc0803'
repository = 'MSSP607'

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

Changed directory to: /content/MSSP607

In [2]:
%pushd "/content/MSSP607/Modules/Week_5"

/content/MSSP607/Modules/Week_5

['/content/MSSP607']

In [3]:
!ls

aapl.csv  amzn.csv  fb.csv  goog.csv  nflx.csv	README.md

In [4]:
### Read the files into dataframes
import pandas as pd
import glob

files = glob.glob("*.csv")

dfs = [pd.read_csv(file) for file in files]

In [16]:
ggle = dfs[0]
fb = dfs[1]
amzn = dfs[2]
nflx = dfs[3]
aapl = dfs[4]

In [19]:
### c

aapl['ticker'] = 'aapl'
amzn['ticker'] = 'amzn'
fb['ticker'] = 'fb'
nflx['ticker'] = 'nflx'
ggle['ticker'] = 'ggle'

### d
df = pd.concat([aapl, amzn, fb, nflx, ggle])
df

           date       open       high        low      close    volume ticker
0    2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   aapl
1    2018-01-03   169.2521   171.2337   168.6929   168.9578  29517899   aapl
2    2018-01-04   169.2619   170.1742   168.8106   169.7426  22434597   aapl
3    2018-01-05   170.1448   172.0381   169.7622   171.6751  23660018   aapl
4    2018-01-08   171.0375   172.2736   170.6255   171.0375  20567766   aapl
..          ...        ...        ...        ...        ...       ...    ...
246  2018-12-24   973.9000  1003.5400   970.1100   976.2200   1590328   ggle
247  2018-12-26   989.0100  1040.0000   983.0000  1039.4600   2373270   ggle
248  2018-12-27  1017.1500  1043.8900   997.0000  1043.8800   2109777   ggle
249  2018-12-28  1049.6200  1055.5600  1033.1000  1037.0800   1413772   ggle
250  2018-12-31  1050.9600  1052.7000  1023.5900  1035.6100   1493722   ggle

[1255 rows x 7 columns]

In [20]:
### e
df.to_csv("faang.csv", index=False)

In [21]:
os.getcwd()

'/content/MSSP607/Modules/Week_5'

In [22]:
!ls

aapl.csv  amzn.csv  faang.csv  fb.csv  goog.csv  nflx.csv  README.md

In [25]:
### f
df["date"] = pd.to_datetime(df["date"])
df["volume"] = df["volume"].astype(int)

df = df.sort_values(["date", "ticker"]).reset_index(drop=True)

df.head()

        date       open       high        low      close    volume ticker
0 2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   aapl
1 2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   amzn
2 2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     fb
3 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   ggle
4 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   nflx

In [26]:
### g
df.sort_values("volume", ascending=False).head(7)

           date      open      high       low     close     volume ticker
712  2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     fb
267  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     fb
287  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     fb
272  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     fb
910  2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   aapl
1225 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   aapl
1060 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   aapl

In [31]:
### h
df_melted = df.melt(id_vars=["date", "ticker"])
df_melted.head(12)

         date ticker variable      value
0  2018-01-02   aapl     open   166.9271
1  2018-01-02   amzn     open  1172.0000
2  2018-01-02     fb     open   177.6800
3  2018-01-02   ggle     open  1048.3400
4  2018-01-02   nflx     open   196.1000
5  2018-01-03   aapl     open   169.2521
6  2018-01-03   amzn     open  1188.3000
7  2018-01-03     fb     open   181.8800
8  2018-01-03   ggle     open  1064.3100
9  2018-01-03   nflx     open   202.0500
10 2018-01-04   aapl     open   169.2619
11 2018-01-04   amzn     open  1205.0000