<a href="https://colab.research.google.com/github/sytluc0803/MSSP607/blob/main/Modules/Week_5/Week_5_Ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import userdata
import os

github_token = userdata.get('Git_Key')
owner = 'sytluc0803'
repository = 'MSSP607'

clone_url = f'https://x-access-token:{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

Changed directory to: /content/MSSP607/MSSP607

In [7]:
%pushd "/content/MSSP607/Modules/Week_5"

/content/MSSP607/Modules/Week_5

['/content/MSSP607/MSSP607']

In [8]:
!ls

aapl.csv  amzn.csv  fb.csv  goog.csv  nflx.csv	README.md  Week_5_Ex.ipynb

In [9]:
### Read the files into dataframes
import pandas as pd
import glob

files = glob.glob("*.csv")

dfs = [pd.read_csv(file) for file in files]

In [10]:
ggle = dfs[0]
fb = dfs[1]
amzn = dfs[2]
nflx = dfs[3]
aapl = dfs[4]

In [11]:
### c

aapl['ticker'] = 'aapl'
amzn['ticker'] = 'amzn'
fb['ticker'] = 'fb'
nflx['ticker'] = 'nflx'
ggle['ticker'] = 'ggle'

### d
df = pd.concat([aapl, amzn, fb, nflx, ggle])
df

           date      open      high       low     close    volume ticker
0    2018-01-02  177.6800  181.5800  177.5500  181.4200  18151903   aapl
1    2018-01-03  181.8800  184.7800  181.3300  184.6700  16886563   aapl
2    2018-01-04  184.9000  186.2100  184.0996  184.3300  13880896   aapl
3    2018-01-05  185.5900  186.9000  184.9300  186.8500  13574535   aapl
4    2018-01-08  187.2000  188.9000  186.3300  188.2800  17994726   aapl
..          ...       ...       ...       ...       ...       ...    ...
246  2018-12-24  147.5173  150.9027  145.9639  146.2029  37169232   ggle
247  2018-12-26  147.6666  156.5585  146.0934  156.4987  58582544   ggle
248  2018-12-27  155.1744  156.1004  149.4291  155.4831  53117065   ggle
249  2018-12-28  156.8273  157.8430  153.8899  155.5627  42291424   ggle
250  2018-12-31  157.8529  158.6794  155.8117  157.0663  35003466   ggle

[1255 rows x 7 columns]

In [12]:
### e
df.to_csv("faang.csv", index=False)

In [13]:
os.getcwd()

'/content/MSSP607/Modules/Week_5'

In [14]:
!ls

aapl.csv  faang.csv  goog.csv  README.md
amzn.csv  fb.csv     nflx.csv  Week_5_Ex.ipynb

In [15]:
### f
df["date"] = pd.to_datetime(df["date"])
df["volume"] = df["volume"].astype(int)

df = df.sort_values(["date", "ticker"]).reset_index(drop=True)

df.head()

        date       open       high        low      close    volume ticker
0 2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903   aapl
1 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   amzn
2 2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494     fb
3 2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   ggle
4 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   nflx

In [16]:
### g
df.sort_values("volume", ascending=False).head(7)

           date      open      high       low     close     volume ticker
710  2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668   aapl
265  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768   aapl
285  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634   aapl
270  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834   aapl
913  2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   ggle
1228 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   ggle
1063 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   ggle

In [17]:
### h
df_melted = df.melt(id_vars=["date", "ticker"])
df_melted.head(12)

         date ticker variable      value
0  2018-01-02   aapl     open   177.6800
1  2018-01-02   amzn     open  1048.3400
2  2018-01-02     fb     open  1172.0000
3  2018-01-02   ggle     open   166.9271
4  2018-01-02   nflx     open   196.1000
5  2018-01-03   aapl     open   181.8800
6  2018-01-03   amzn     open  1064.3100
7  2018-01-03     fb     open  1188.3000
8  2018-01-03   ggle     open   169.2521
9  2018-01-03   nflx     open   202.0500
10 2018-01-04   aapl     open   184.9000
11 2018-01-04   amzn     open  1088.0000