<a href="https://colab.research.google.com/github/sytluc0803/MSSP607/blob/main/Assignments/Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
from google.colab import userdata
import os

github_token = userdata.get('Git_Key')
owner = 'sytluc0803'
repository = 'MSSP607'

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

Changed directory to: /content/MSSP607

In [3]:
%pushd "/content/MSSP607/Assignments"

/content/MSSP607/Assignments

['/content/MSSP607']

In [4]:
!ls

data_academic_performance.xlsx	README.md

In [6]:
import numpy as np
import pandas as pd
import statistics

df = pd.read_excel('data_academic_performance.xlsx')
df.head()

,COD_S11,GENDER,EDU_FATHER,EDU_MOTHER,OCC_FATHER,OCC_MOTHER,STRATUM,SISBEN,PEOPLE_HOUSE,Unnamed: 9,...,CC_PRO,ENG_PRO,WC_PRO,FEP_PRO,G_SC,PERCENTILE,2ND_DECILE,QUARTILE,SEL,SEL_IHE
0,SB11201210000129,F,Incomplete Professional Education,Complete technique or technology,Technical or professional level employee,Home,Stratum 4,It is not classified by the SISBEN,Three,NaN,...,71,93,79,181,180,91,5,4,2,2
1,SB11201210000137,F,Complete Secundary,Complete professional education,Entrepreneur,Independent professional,Stratum 5,It is not classified by the SISBEN,Three,NaN,...,86,98,78,201,182,92,5,4,4,4
2,SB11201210005154,M,Not sure,Not sure,Independent,Home,Stratum 2,Level 2,Five,NaN,...,18,43,22,113,113,7,1,1,1,1
3,SB11201210007504,F,Not sure,Not sure,Other occupation,Independent,Stratum 2,It is not classified by the SISBEN,Three,NaN,...,76,80,48,137,157,67,4,3,2,2
4,SB11201210007548,M,Complete professional education,Complete professional education,Executive,Home,Stratum 4,It is not classified by the SISBEN,One,NaN,...,98,100,71,189,198,98,5,4,4,2

In [20]:
df.columns.tolist()

['COD_S11',
 'GENDER',
 'EDU_FATHER',
 'EDU_MOTHER',
 'OCC_FATHER',
 'OCC_MOTHER',
 'STRATUM',
 'SISBEN',
 'PEOPLE_HOUSE',
 'Unnamed: 9',
 'INTERNET',
 'TV',
 'COMPUTER',
 'WASHING_MCH',
 'MIC_OVEN',
 'CAR',
 'DVD',
 'FRESH',
 'PHONE',
 'MOBILE',
 'REVENUE',
 'JOB',
 'SCHOOL_NAME',
 'SCHOOL_NAT',
 'SCHOOL_TYPE',
 'MAT_S11',
 'CR_S11',
 'CC_S11',
 'BIO_S11',
 'ENG_S11',
 'Cod_SPro',
 'UNIVERSITY',
 'ACADEMIC_PROGRAM',
 'QR_PRO',
 'CR_PRO',
 'CC_PRO',
 'ENG_PRO',
 'WC_PRO',
 'FEP_PRO',
 'G_SC',
 'PERCENTILE',
 '2ND_DECILE',
 'QUARTILE',
 'SEL',
 'SEL_IHE']

In [23]:
df['EDU_FATHER'].value_counts()

df['EDU_MOTHER'].value_counts()

EDU_MOTHER
Complete Secundary                       3106
Complete professional education          3059
Complete technique or technology         1495
Incomplete Secundary                     1056
Postgraduate education                    997
Complete primary                          713
Incomplete primary                        541
Incomplete Professional Education         502
0                                         388
Incomplete technical or technological     341
Not sure                                  179
Ninguno                                    34
Name: count, dtype: int64